declare
    l_count number;
begin
    select count(*) into l_count
      from user_tables
     where table_name = 'EBA_DEMO_CARD_TASK';

    if l_count = 0 then
        execute immediate q'[
            create table eba_demo_card_task (
                id number generated by default on null as identity
                   constraint eba_demo_card_task_id_pk primary key,
                title varchar2(255) not null,
                description varchar2(4000),
                status varchar2(30) not null
                    constraint eba_demo_card_task_status_cc
                    check (status in ('TODO', 'IN_PROGRESS', 'DONE')),
                priority varchar2(30) not null
                    constraint eba_demo_card_task_priority_cc
                    check (priority in ('LOW', 'MEDIUM', 'HIGH', 'URGENT')),
                assignee varchar2(255),
                sort_order number default 0 not null,
                created timestamp with time zone default systimestamp not null,
                created_by varchar2(255) default coalesce(sys_context('APEX$SESSION','APP_USER'), user) not null,
                updated timestamp with time zone default systimestamp not null,
                updated_by varchar2(255) default coalesce(sys_context('APEX$SESSION','APP_USER'), user) not null
            )
        ]';

        execute immediate q'[
            comment on table eba_demo_card_task is 'Kanban task table for the Sample Cards APEX application demo'
        ]';

        execute immediate q'[
            comment on column eba_demo_card_task.id is 'Primary key'
        ]';

        execute immediate q'[
            comment on column eba_demo_card_task.title is 'Task title displayed as card title'
        ]';

        execute immediate q'[
            comment on column eba_demo_card_task.description is 'Task description displayed as card body'
        ]';

        execute immediate q'[
            comment on column eba_demo_card_task.status is 'Kanban status: TODO, IN_PROGRESS, DONE'
        ]';

        execute immediate q'[
            comment on column eba_demo_card_task.priority is 'Task priority: LOW, MEDIUM, HIGH, URGENT'
        ]';

        execute immediate q'[
            comment on column eba_demo_card_task.assignee is 'Person assigned to the task'
        ]';

        execute immediate q'[
            comment on column eba_demo_card_task.sort_order is 'Display order within each status column'
        ]';

        execute immediate q'[
            comment on column eba_demo_card_task.created is 'Record creation timestamp'
        ]';

        execute immediate q'[
            comment on column eba_demo_card_task.created_by is 'User who created the record'
        ]';

        execute immediate q'[
            comment on column eba_demo_card_task.updated is 'Record last modified timestamp'
        ]';

        execute immediate q'[
            comment on column eba_demo_card_task.updated_by is 'User who last modified the record'
        ]';
    end if;
end;
/
